# Generated by Django 4.1.3 on 2022-12-04 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('salary', models.IntegerField(default=600)),
                ('working_since', models.DateField()),
                ('employee_picture', models.ImageField(blank=True, null=True, upload_to='employee_pictures/')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='employees.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('date', models.DateField()),
                ('attending_department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='employees.departments')),
                ('attending_extra', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
            ],
        ),
        migrations.AddField(
            model_name='departments',
            name='employees',
            field=models.ManyToManyField(to='employees.employee'),
        ),
    ]
