# Generated by Django 4.1.2 on 2022-11-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('MANAGEMENT', 'Management'), ('ACCOUNTING', 'Accounting'), ('HR', 'HR'), ('LOGISTICS', 'Logistics'), ('WAREHOUSE', 'Warehouse'), ('NOT ASSIGNED', 'Not Assigned')], default='NOT ASSIGNED', max_length=20),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
