# Generated by Django 4.1.3 on 2022-12-04 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='employees',
            field=models.ManyToManyField(blank=True, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attending_extra',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employee'),
        ),
    ]
