# Generated by Django 4.1.3 on 2022-12-04 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_departments_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attending_extra',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employee'),
        ),
    ]
