# Generated by Django 4.1.2 on 2022-11-27 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_department_alter_employee_employee_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default='Not assigned', max_length=20, on_delete=django.db.models.deletion.PROTECT, to='employees.department'),
        ),
    ]
