# Generated by Django 4.1.3 on 2022-12-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_event_attending_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attending_extra',
        ),
        migrations.AddField(
            model_name='event',
            name='attending_extra',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='employees.employee'),
        ),
    ]
