# Generated by Django 4.1.3 on 2022-12-05 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_event_attending_extra_event_attending_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attending_department',
            field=models.ForeignKey(default='Not specified', on_delete=django.db.models.deletion.PROTECT, to='employees.departments'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attending_extra',
            field=models.ManyToManyField(blank=True, default='Not specified', to='employees.employee'),
        ),
    ]
