# Generated by Django 4.1.2 on 2022-11-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_employee_department_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Accounting', 'Accounting'), ('Warehouse', 'Warehouse'), ('Logistics', 'Logistics'), ('Management', 'Management'), ('HR', 'HR')], default='Not assigned', max_length=20),
        ),
    ]
