# Generated by Django 4.1.3 on 2022-12-05 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attending_extra',
        ),
        migrations.AlterField(
            model_name='event',
            name='attending_department',
            field=models.ForeignKey(default='Not specified', on_delete=django.db.models.deletion.CASCADE, to='employees.departments'),
        ),
    ]
